#!/usr/bin/env python3
"""
Create Companion — Instantiate a new wrapper from the Kay source + Template persona layer.

Copies Kay's engine infrastructure (the battle-tested code), overlays the Template's
persona system (persona_loader, module_loader, entity_prompts), and replaces hardcoded
Kay-specific references with persona-driven alternatives.

Usage:
  python create_companion.py MyCompanion        # Creates D:/Wrappers/MyCompanion/
  python create_companion.py MyCompanion --wizard  # Also runs setup wizard after copy
  python create_companion.py MyCompanion --import ./docs/  # Copy + document import

Run from D:/Wrappers/
"""

import os
import sys
import shutil
import re
import argparse
from pathlib import Path

WRAPPERS_ROOT = os.path.dirname(os.path.abspath(__file__))
KAY_DIR = os.path.join(WRAPPERS_ROOT, "Kay")
TEMPLATE_DIR = os.path.join(WRAPPERS_ROOT, "Template")

# Files/dirs to copy from Kay (the engine infrastructure)
KAY_COPY_LIST = [
    # Core engine
    "engines/",
    "integrations/",
    "utils/",
    "utilities/",
    "services/",
    # Core files
    "main.py",
    "main_bridge.py",
    "agent_state.py",
    "config.py",
    "protocol_engine.py",
    "context_filter.py",
    "glyph_decoder.py",
    "glyph_vocabulary.py",
    "log_router.py",
    "tab_methods.py",
    "tab_system.py",
    "resonance_memory.py",
    "terminal_dashboard.py",
    # Media
    "media_context_builder.py",
    "media_ingest.py",
    "media_orchestrator.py",
    "media_retrieval.py",
    "media_watcher.py",
    # Memory
    "memory_forest.py",
    # Documents
    "document_manager.py",
    "document_manager_ui.py",
    # UI
    "autonomous_ui.py",
    "autonomous_ui_integration.py",
    "curation_ui.py",
    "curation_ui_integration.py",
    "purge_reserve_ui.py",
    # Web
    "web_scraping_tools.py",
    # Voice
    "voice_handler.py",
    "voice_interface.py",
    "voice_ui_integration.py",
    # Config
    "requirements.txt",
    "requirements_multiprovider.txt",
]

# Files/dirs to SKIP (Kay-specific, replaced by Template)
KAY_SKIP = {
    "kay_prompts.py",
    "kay_cli.py",
    "kay_ui.py",
    "kay_document_reader.py",
    "kay_scratchpad_tools.py",
    "kay_session_logs/",
    "launch_kay.bat",
    "K-0/",
    "chroma_db/",
    "memory/",
    "sessions/",
    "saved_sessions/",
    "chronicle/",
    "data/",
    "state/",
    "config.json",  # Generated by persona_loader
    ".env",
    "__pycache__/",
    "deprecated/",
    "fixes/",
    "temp_scratchpad_fix/",
    "sessions_backup_20251119_140638/",
    "memorybackup_20251021_210216/",
    "screenshots/",
    "themes/",   # Will be generated from persona config
    "ornate_assets/",
    "Paint/",
    ".claude/",
    ".git/",
    "nul",
    "pip",
}

# Files to copy from Template (overlay on top of Kay infrastructure)
TEMPLATE_COPY_LIST = [
    "persona/",
    "persona_loader.py",
    "entity_prompts.py",
    "module_loader.py",
    "modules.json",
    "setup_wizard.py",
    "launch.bat",
    "env_template.txt",
    "README.md",
]


def copy_item(src: str, dst: str, item: str):
    """Copy a file or directory from src to dst."""
    src_path = os.path.join(src, item)
    dst_path = os.path.join(dst, item)

    if not os.path.exists(src_path):
        print(f"  SKIP (not found): {item}")
        return False

    if item.endswith("/"):
        # Directory copy
        if os.path.exists(dst_path):
            shutil.rmtree(dst_path)
        shutil.copytree(src_path, dst_path,
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".git"))
        print(f"  ✓ DIR  {item}")
    else:
        os.makedirs(os.path.dirname(dst_path), exist_ok=True)
        shutil.copy2(src_path, dst_path)
        print(f"  ✓ FILE {item}")
    return True


def patch_kay_references(companion_dir: str):
    """Replace hardcoded Kay references with persona_loader calls.
    
    This is the surgical part — find every place Kay's name is hardcoded
    and replace it with persona-driven alternatives.
    """
    patches_applied = 0

    for root, dirs, files in os.walk(companion_dir):
        # Skip non-Python files and persona dir
        dirs[:] = [d for d in dirs if d not in ("__pycache__", "persona", ".git")]

        for fname in files:
            if not fname.endswith(".py"):
                continue

            filepath = os.path.join(root, fname)
            try:
                with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                    content = f.read()
            except Exception:
                continue

            original = content

            # --- Import replacements ---
            # Replace kay_prompts imports with entity_prompts
            content = re.sub(
                r'from kay_prompts import (\w+)',
                r'from entity_prompts import \1',
                content
            )
            content = content.replace(
                'import kay_prompts',
                'import entity_prompts as kay_prompts'
            )

            # --- String literal replacements ---
            # Replace hardcoded entity name in set_entity calls
            content = re.sub(
                r'set_entity\(["\']kay["\']\)',
                'set_entity(persona.entity_id if persona else "companion")',
                content
            )
            # Add persona import if we made set_entity changes
            if 'persona.entity_id' in content and 'from persona_loader' not in content:
                # Add import after the entity_log import
                content = content.replace(
                    'from shared.entity_log import',
                    'from persona_loader import persona\nfrom shared.entity_log import'
                )

            # Replace hardcoded room entity additions
            content = re.sub(
                r'room\.add_entity\(["\']kay["\']',
                'room.add_entity(persona.entity_id',
                content
            )
            content = re.sub(
                r'room\.add_entity\(["\']reed["\']',
                'room.add_entity(persona.entity_id',
                content
            )

            # Replace hardcoded entity_id= strings
            content = re.sub(
                r'entity_id=["\']kay["\']',
                'entity_id=persona.entity_id',
                content
            )
            content = re.sub(
                r'entity_id=["\']reed["\']',
                'entity_id=persona.entity_id',
                content
            )

            # Replace hardcoded color in room
            content = re.sub(
                r'color=["\']#2D1B4E["\']',
                f'color=persona.room_config.get("color", "#4A90D9")',
                content
            )

            # Replace KAY_WRAPPER_DIR references in nexus files
            content = content.replace('KAY_WRAPPER_DIR', 'WRAPPER_DIR')
            content = content.replace('REED_WRAPPER_DIR', 'WRAPPER_DIR')

            # Replace hardcoded directory references
            content = content.replace('"Kay")', f'"{os.path.basename(companion_dir)}")')
            content = content.replace('"Reed")', f'"{os.path.basename(companion_dir)}")')

            # Write back if changed
            if content != original:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                patches_applied += 1
                rel = os.path.relpath(filepath, companion_dir)
                print(f"  PATCH  {rel}")

    return patches_applied


def create_empty_dirs(companion_dir: str):
    """Create the empty directory structure a fresh wrapper needs."""
    dirs = [
        "memory",
        "memory/vector_db",
        "memory/resonant",
        "memory/layers",
        "sessions",
        "data",
        "logs",
        "chronicle",
        "inputs",
    ]
    for d in dirs:
        path = os.path.join(companion_dir, d)
        os.makedirs(path, exist_ok=True)
    print(f"  ✓ Created {len(dirs)} empty directories")


def create_companion(name: str, run_wizard: bool = False, import_path: str = None):
    """Create a new companion wrapper directory."""
    companion_dir = os.path.join(WRAPPERS_ROOT, name)

    if os.path.exists(companion_dir):
        print(f"\n  ERROR: {companion_dir} already exists.")
        print(f"  Delete it first or choose a different name.")
        sys.exit(1)

    print(f"\n{'=' * 60}")
    print(f"  CREATING COMPANION: {name}")
    print(f"  Directory: {companion_dir}")
    print(f"{'=' * 60}")

    os.makedirs(companion_dir)

    # Step 1: Copy engine infrastructure from Kay
    print(f"\n  [1/5] Copying engine infrastructure from Kay...")
    copied = 0
    for item in KAY_COPY_LIST:
        if copy_item(KAY_DIR, companion_dir, item):
            copied += 1
    print(f"  Copied {copied} items from Kay")

    # Step 2: Overlay Template persona layer
    print(f"\n  [2/5] Overlaying Template persona layer...")
    for item in TEMPLATE_COPY_LIST:
        copy_item(TEMPLATE_DIR, companion_dir, item)

    # Step 3: Create empty directories
    print(f"\n  [3/5] Creating directory structure...")
    create_empty_dirs(companion_dir)

    # Step 4: Patch Kay-specific references
    print(f"\n  [4/5] Patching hardcoded references...")
    patched = patch_kay_references(companion_dir)
    print(f"  Patched {patched} files")

    # Step 5: Run wizard if requested
    if run_wizard or import_path:
        print(f"\n  [5/5] Running setup wizard...")
        os.chdir(companion_dir)
        wizard_args = [sys.executable, "setup_wizard.py"]
        if import_path:
            wizard_args.extend(["--import", import_path])
        os.execv(sys.executable, wizard_args)
    else:
        print(f"\n  [5/5] Skipping wizard (run manually later)")

    # Done
    print(f"\n{'=' * 60}")
    print(f"  ✓ {name} created at {companion_dir}")
    print(f"")
    print(f"  Next steps:")
    print(f"    1. cd {companion_dir}")
    print(f"    2. python setup_wizard.py")
    print(f"    3. cp env_template.txt .env  (add your API key)")
    print(f"    4. python main.py")
    print(f"{'=' * 60}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Create a new companion wrapper from the Template."
    )
    parser.add_argument(
        "name",
        help="Name for the companion directory (e.g., 'Aria', 'Sage')"
    )
    parser.add_argument(
        "--wizard", action="store_true",
        help="Run the setup wizard after creating the directory"
    )
    parser.add_argument(
        "--import", dest="import_path", metavar="PATH",
        help="Import persona from documents (runs wizard in import mode)"
    )
    args = parser.parse_args()

    # Validate
    if not os.path.exists(KAY_DIR):
        print(f"  ERROR: Kay directory not found at {KAY_DIR}")
        print(f"  This script copies engine code from Kay as the reference implementation.")
        sys.exit(1)

    if not os.path.exists(TEMPLATE_DIR):
        print(f"  ERROR: Template directory not found at {TEMPLATE_DIR}")
        print(f"  Create it first or check your Wrappers directory.")
        sys.exit(1)

    create_companion(args.name, run_wizard=args.wizard, import_path=args.import_path)


if __name__ == "__main__":
    main()
